# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - README.md

variables:
  rootDir: 'react-app-phase1'
  buildDir: '$(rootDir)/build'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Azure für Bildungseinrichtungen(1169a369-f083-425e-8a9b-45b15bbfa7ae)'
    KeyVaultName: 'zomato-api-key'
    SecretsFilter: '*'
    RunAsPreJob: false

- script: |
    cd $(rootDir)
    echo "REACT_APP_ZOMATO_KEY=$(zomatoApiKey)" > .env.production
    npm install
    npm run build
    cd ..
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(buildDir)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
